version: '3.1'
services:
  onticards-web:
    container_name: onticards-web
    image: registry.cn-hongkong.aliyuncs.com/souther/onticards-web:1.0.0
    restart: always
    environment:
      CONSOLE_API_URL: 'http://127.0.0.1'
    networks:
      - back

networks:
  back:
    external: true
